FROM ubuntu:latest
MAINTAINER username
WORKDIR /home/projects

RUN apt-get update && apt-get install -y \
  vim \
  gcc \
  g++ \
  binutils \
  build-essential \
  dosfstools \
  mtools \
  libc6-i386 \

